on:
  push:
    branches:
      - main

jobs:
  make:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - dns
    steps:
      - uses: actions/checkout@v3

      - run: make -C ${{ matrix.project }}
